External module
Tanaguru/tanaguru2020-webapp pull request #81
Opened 2021-06-23 10:00 UTC by lpedrau

2021-06-23 12:34 UTC, rcharre requested changes

2021-06-23 12:34 UTC, rcharre commented on src/views/ExternalModule.vue
> +			}
Il faudrait deplacer ça dans une methode

2021-06-23 12:34 UTC, rcharre commented on src/views/ExternalModule.vue
> +			return true
A quoi ca sert ?

2021-06-23 12:34 UTC, rcharre commented on src/views/ExternalModule.vue
> +						this.$refs.iframe.contentWindow.postMessage({'name': 'init-locale','locale': localStorage.getItem('locale')}, '*')
A deplacer dans une methode permettant de changer la langue de l'iframe

2021-06-24 15:09 UTC, lpedrau commented on src/views/ExternalModule.vue
> +			return true
en effet, supprimé car ne sert à rien ici

2021-06-30 14:00 UTC, rcharre requested changes

2021-06-30 14:00 UTC, rcharre commented on public/assets/config/tanaguru-modules.js
> +];
Est ce que la CICD gere cette conf ?

2021-06-30 14:02 UTC, lpedrau commented on public/assets/config/tanaguru-modules.js
> +];
je n'ai pas encore ajouté cette clé dans la CICD, je vais me pencher dessus maintenant

2021-06-30 14:34 UTC, lpedrau commented on public/assets/config/tanaguru-modules.js
> +];
normalement c'est ok, à tester, jenkins mis à jour + tanaguru2020-docker mis à jour (voir PR) + jenkins config files mises à jour.. J'ai à chaque fois mis à vide TANAGURU_MODULES=[];

2021-07-08 07:52 UTC, rcharre approved these changes

2021-07-08 07:52 UTC, merged